[project]
name = "llm-from-scratch"
version = "0.1.0"
description = "Exercised from LLM from Scratch book"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mypy>=1.14.1",
    "ruff>=0.9.2",
]
